package catan.player;

public enum PlayerAction {
	
	NONE, PLACE_ROAD, PLACE_ROAD_START, PLACE_TOWN, PLACE_TOWN_START, PLACE_TOWN_START_WITH_RESOURCES, UPGRADE_CITY, MOVE_ROBBER, CHOOSE_PLAYER_TO_STEAL_FROM;

}
